theme: jekyll-theme-minimal
include: ["_sources","_static"]

title: <a href="/#"><img src="project_files/logo/pyfea_text.png" alt="PyFEA Logo"> PyFEA</a>
google_analytics: UA-116335955-5
show_downloads: false

github:
  zip_url: https://github.com/Christophe-Foyer/PyFEA/zipball/master
  tar_url: https://github.com/Christophe-Foyer/PyFEA/tarball/master
