theme: jekyll-theme-minimal
include: ["_sources","_static"]

title: <a href="http://pyfea.cfoyer.com"><img src="project_files/logo/pyfea_color.png" alt="PyFEA Logo"></a> PyFEA
google_analytics: 
show_downloads: false

github:
  zip_url: https://github.com/Christophe-Foyer/PyFEA/zipball/master
  tar_url: https://github.com/Christophe-Foyer/PyFEA/tarball/master